//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("SATModel", "FK_Courses_CourseStatus1", "CourseStatus", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(SATProject.CourseStatu), "Courses", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(SATProject.Cours), true)]
[assembly: EdmRelationshipAttribute("SATModel", "FK_ScheduledClasses_Courses", "Courses", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(SATProject.Cours), "ScheduledClasses", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(SATProject.ScheduledClass), true)]
[assembly: EdmRelationshipAttribute("SATModel", "FK_Enrollments_ScheduledClasses", "ScheduledClasses", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(SATProject.ScheduledClass), "Enrollments", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(SATProject.Enrollment), true)]
[assembly: EdmRelationshipAttribute("SATModel", "FK_Enrollments_Students", "Students", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(SATProject.Student), "Enrollments", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(SATProject.Enrollment), true)]
[assembly: EdmRelationshipAttribute("SATModel", "FK_ScheduledClasses_ScheduledClassStatus1", "ScheduledClassStatus", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(SATProject.ScheduledClassStatu), "ScheduledClasses", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(SATProject.ScheduledClass), true)]
[assembly: EdmRelationshipAttribute("SATModel", "FK_Students_StudentStatus", "StudentStatus", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(SATProject.StudentStatu), "Students", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(SATProject.Student), true)]

#endregion

namespace SATProject
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class SATEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new SATEntities object using the connection string found in the 'SATEntities' section of the application configuration file.
        /// </summary>
        public SATEntities() : base("name=SATEntities", "SATEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new SATEntities object.
        /// </summary>
        public SATEntities(string connectionString) : base(connectionString, "SATEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new SATEntities object.
        /// </summary>
        public SATEntities(EntityConnection connection) : base(connection, "SATEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Cours> Courses
        {
            get
            {
                if ((_Courses == null))
                {
                    _Courses = base.CreateObjectSet<Cours>("Courses");
                }
                return _Courses;
            }
        }
        private ObjectSet<Cours> _Courses;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<CourseStatu> CourseStatus
        {
            get
            {
                if ((_CourseStatus == null))
                {
                    _CourseStatus = base.CreateObjectSet<CourseStatu>("CourseStatus");
                }
                return _CourseStatus;
            }
        }
        private ObjectSet<CourseStatu> _CourseStatus;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Enrollment> Enrollments
        {
            get
            {
                if ((_Enrollments == null))
                {
                    _Enrollments = base.CreateObjectSet<Enrollment>("Enrollments");
                }
                return _Enrollments;
            }
        }
        private ObjectSet<Enrollment> _Enrollments;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ScheduledClass> ScheduledClasses
        {
            get
            {
                if ((_ScheduledClasses == null))
                {
                    _ScheduledClasses = base.CreateObjectSet<ScheduledClass>("ScheduledClasses");
                }
                return _ScheduledClasses;
            }
        }
        private ObjectSet<ScheduledClass> _ScheduledClasses;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ScheduledClassStatu> ScheduledClassStatus
        {
            get
            {
                if ((_ScheduledClassStatus == null))
                {
                    _ScheduledClassStatus = base.CreateObjectSet<ScheduledClassStatu>("ScheduledClassStatus");
                }
                return _ScheduledClassStatus;
            }
        }
        private ObjectSet<ScheduledClassStatu> _ScheduledClassStatus;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Student> Students
        {
            get
            {
                if ((_Students == null))
                {
                    _Students = base.CreateObjectSet<Student>("Students");
                }
                return _Students;
            }
        }
        private ObjectSet<Student> _Students;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<StudentStatu> StudentStatus
        {
            get
            {
                if ((_StudentStatus == null))
                {
                    _StudentStatus = base.CreateObjectSet<StudentStatu>("StudentStatus");
                }
                return _StudentStatus;
            }
        }
        private ObjectSet<StudentStatu> _StudentStatus;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Courses EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCourses(Cours cours)
        {
            base.AddObject("Courses", cours);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the CourseStatus EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCourseStatus(CourseStatu courseStatu)
        {
            base.AddObject("CourseStatus", courseStatu);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Enrollments EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToEnrollments(Enrollment enrollment)
        {
            base.AddObject("Enrollments", enrollment);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ScheduledClasses EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToScheduledClasses(ScheduledClass scheduledClass)
        {
            base.AddObject("ScheduledClasses", scheduledClass);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ScheduledClassStatus EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToScheduledClassStatus(ScheduledClassStatu scheduledClassStatu)
        {
            base.AddObject("ScheduledClassStatus", scheduledClassStatu);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Students EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToStudents(Student student)
        {
            base.AddObject("Students", student);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the StudentStatus EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToStudentStatus(StudentStatu studentStatu)
        {
            base.AddObject("StudentStatus", studentStatu);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SATModel", Name="Cours")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Cours : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Cours object.
        /// </summary>
        /// <param name="courseId">Initial value of the courseId property.</param>
        /// <param name="courseName">Initial value of the courseName property.</param>
        /// <param name="statusId">Initial value of the statusId property.</param>
        public static Cours CreateCours(global::System.Int32 courseId, global::System.String courseName, global::System.Int32 statusId)
        {
            Cours cours = new Cours();
            cours.courseId = courseId;
            cours.courseName = courseName;
            cours.statusId = statusId;
            return cours;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 courseId
        {
            get
            {
                return _courseId;
            }
            set
            {
                if (_courseId != value)
                {
                    OncourseIdChanging(value);
                    ReportPropertyChanging("courseId");
                    _courseId = StructuralObject.SetValidValue(value, "courseId");
                    ReportPropertyChanged("courseId");
                    OncourseIdChanged();
                }
            }
        }
        private global::System.Int32 _courseId;
        partial void OncourseIdChanging(global::System.Int32 value);
        partial void OncourseIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String courseName
        {
            get
            {
                return _courseName;
            }
            set
            {
                OncourseNameChanging(value);
                ReportPropertyChanging("courseName");
                _courseName = StructuralObject.SetValidValue(value, false, "courseName");
                ReportPropertyChanged("courseName");
                OncourseNameChanged();
            }
        }
        private global::System.String _courseName;
        partial void OncourseNameChanging(global::System.String value);
        partial void OncourseNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String courseDescription
        {
            get
            {
                return _courseDescription;
            }
            set
            {
                OncourseDescriptionChanging(value);
                ReportPropertyChanging("courseDescription");
                _courseDescription = StructuralObject.SetValidValue(value, true, "courseDescription");
                ReportPropertyChanged("courseDescription");
                OncourseDescriptionChanged();
            }
        }
        private global::System.String _courseDescription;
        partial void OncourseDescriptionChanging(global::System.String value);
        partial void OncourseDescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String department
        {
            get
            {
                return _department;
            }
            set
            {
                OndepartmentChanging(value);
                ReportPropertyChanging("department");
                _department = StructuralObject.SetValidValue(value, true, "department");
                ReportPropertyChanged("department");
                OndepartmentChanged();
            }
        }
        private global::System.String _department;
        partial void OndepartmentChanging(global::System.String value);
        partial void OndepartmentChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String curriculum
        {
            get
            {
                return _curriculum;
            }
            set
            {
                OncurriculumChanging(value);
                ReportPropertyChanging("curriculum");
                _curriculum = StructuralObject.SetValidValue(value, true, "curriculum");
                ReportPropertyChanged("curriculum");
                OncurriculumChanged();
            }
        }
        private global::System.String _curriculum;
        partial void OncurriculumChanging(global::System.String value);
        partial void OncurriculumChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String notes
        {
            get
            {
                return _notes;
            }
            set
            {
                OnnotesChanging(value);
                ReportPropertyChanging("notes");
                _notes = StructuralObject.SetValidValue(value, true, "notes");
                ReportPropertyChanged("notes");
                OnnotesChanged();
            }
        }
        private global::System.String _notes;
        partial void OnnotesChanging(global::System.String value);
        partial void OnnotesChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 statusId
        {
            get
            {
                return _statusId;
            }
            set
            {
                OnstatusIdChanging(value);
                ReportPropertyChanging("statusId");
                _statusId = StructuralObject.SetValidValue(value, "statusId");
                ReportPropertyChanged("statusId");
                OnstatusIdChanged();
            }
        }
        private global::System.Int32 _statusId;
        partial void OnstatusIdChanging(global::System.Int32 value);
        partial void OnstatusIdChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SATModel", "FK_Courses_CourseStatus1", "CourseStatus")]
        public CourseStatu CourseStatu
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CourseStatu>("SATModel.FK_Courses_CourseStatus1", "CourseStatus").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CourseStatu>("SATModel.FK_Courses_CourseStatus1", "CourseStatus").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<CourseStatu> CourseStatuReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CourseStatu>("SATModel.FK_Courses_CourseStatus1", "CourseStatus");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<CourseStatu>("SATModel.FK_Courses_CourseStatus1", "CourseStatus", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SATModel", "FK_ScheduledClasses_Courses", "ScheduledClasses")]
        public EntityCollection<ScheduledClass> ScheduledClasses
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<ScheduledClass>("SATModel.FK_ScheduledClasses_Courses", "ScheduledClasses");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<ScheduledClass>("SATModel.FK_ScheduledClasses_Courses", "ScheduledClasses", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SATModel", Name="CourseStatu")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class CourseStatu : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new CourseStatu object.
        /// </summary>
        /// <param name="cSID">Initial value of the CSID property.</param>
        /// <param name="cSName">Initial value of the CSName property.</param>
        public static CourseStatu CreateCourseStatu(global::System.Int32 cSID, global::System.String cSName)
        {
            CourseStatu courseStatu = new CourseStatu();
            courseStatu.CSID = cSID;
            courseStatu.CSName = cSName;
            return courseStatu;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CSID
        {
            get
            {
                return _CSID;
            }
            set
            {
                if (_CSID != value)
                {
                    OnCSIDChanging(value);
                    ReportPropertyChanging("CSID");
                    _CSID = StructuralObject.SetValidValue(value, "CSID");
                    ReportPropertyChanged("CSID");
                    OnCSIDChanged();
                }
            }
        }
        private global::System.Int32 _CSID;
        partial void OnCSIDChanging(global::System.Int32 value);
        partial void OnCSIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CSName
        {
            get
            {
                return _CSName;
            }
            set
            {
                OnCSNameChanging(value);
                ReportPropertyChanging("CSName");
                _CSName = StructuralObject.SetValidValue(value, false, "CSName");
                ReportPropertyChanged("CSName");
                OnCSNameChanged();
            }
        }
        private global::System.String _CSName;
        partial void OnCSNameChanging(global::System.String value);
        partial void OnCSNameChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SATModel", "FK_Courses_CourseStatus1", "Courses")]
        public EntityCollection<Cours> Courses
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Cours>("SATModel.FK_Courses_CourseStatus1", "Courses");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Cours>("SATModel.FK_Courses_CourseStatus1", "Courses", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SATModel", Name="Enrollment")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Enrollment : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Enrollment object.
        /// </summary>
        /// <param name="enrollmentId">Initial value of the enrollmentId property.</param>
        /// <param name="scheduledClassId">Initial value of the scheduledClassId property.</param>
        /// <param name="studentId">Initial value of the studentId property.</param>
        /// <param name="enrollmentDate">Initial value of the enrollmentDate property.</param>
        public static Enrollment CreateEnrollment(global::System.Int32 enrollmentId, global::System.Int32 scheduledClassId, global::System.Int32 studentId, global::System.DateTime enrollmentDate)
        {
            Enrollment enrollment = new Enrollment();
            enrollment.enrollmentId = enrollmentId;
            enrollment.scheduledClassId = scheduledClassId;
            enrollment.studentId = studentId;
            enrollment.enrollmentDate = enrollmentDate;
            return enrollment;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 enrollmentId
        {
            get
            {
                return _enrollmentId;
            }
            set
            {
                if (_enrollmentId != value)
                {
                    OnenrollmentIdChanging(value);
                    ReportPropertyChanging("enrollmentId");
                    _enrollmentId = StructuralObject.SetValidValue(value, "enrollmentId");
                    ReportPropertyChanged("enrollmentId");
                    OnenrollmentIdChanged();
                }
            }
        }
        private global::System.Int32 _enrollmentId;
        partial void OnenrollmentIdChanging(global::System.Int32 value);
        partial void OnenrollmentIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 scheduledClassId
        {
            get
            {
                return _scheduledClassId;
            }
            set
            {
                OnscheduledClassIdChanging(value);
                ReportPropertyChanging("scheduledClassId");
                _scheduledClassId = StructuralObject.SetValidValue(value, "scheduledClassId");
                ReportPropertyChanged("scheduledClassId");
                OnscheduledClassIdChanged();
            }
        }
        private global::System.Int32 _scheduledClassId;
        partial void OnscheduledClassIdChanging(global::System.Int32 value);
        partial void OnscheduledClassIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 studentId
        {
            get
            {
                return _studentId;
            }
            set
            {
                OnstudentIdChanging(value);
                ReportPropertyChanging("studentId");
                _studentId = StructuralObject.SetValidValue(value, "studentId");
                ReportPropertyChanged("studentId");
                OnstudentIdChanged();
            }
        }
        private global::System.Int32 _studentId;
        partial void OnstudentIdChanging(global::System.Int32 value);
        partial void OnstudentIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime enrollmentDate
        {
            get
            {
                return _enrollmentDate;
            }
            set
            {
                OnenrollmentDateChanging(value);
                ReportPropertyChanging("enrollmentDate");
                _enrollmentDate = StructuralObject.SetValidValue(value, "enrollmentDate");
                ReportPropertyChanged("enrollmentDate");
                OnenrollmentDateChanged();
            }
        }
        private global::System.DateTime _enrollmentDate;
        partial void OnenrollmentDateChanging(global::System.DateTime value);
        partial void OnenrollmentDateChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SATModel", "FK_Enrollments_ScheduledClasses", "ScheduledClasses")]
        public ScheduledClass ScheduledClass
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ScheduledClass>("SATModel.FK_Enrollments_ScheduledClasses", "ScheduledClasses").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ScheduledClass>("SATModel.FK_Enrollments_ScheduledClasses", "ScheduledClasses").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<ScheduledClass> ScheduledClassReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ScheduledClass>("SATModel.FK_Enrollments_ScheduledClasses", "ScheduledClasses");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<ScheduledClass>("SATModel.FK_Enrollments_ScheduledClasses", "ScheduledClasses", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SATModel", "FK_Enrollments_Students", "Students")]
        public Student Student
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Student>("SATModel.FK_Enrollments_Students", "Students").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Student>("SATModel.FK_Enrollments_Students", "Students").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Student> StudentReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Student>("SATModel.FK_Enrollments_Students", "Students");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Student>("SATModel.FK_Enrollments_Students", "Students", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SATModel", Name="ScheduledClass")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ScheduledClass : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ScheduledClass object.
        /// </summary>
        /// <param name="scheduledClassId">Initial value of the scheduledClassId property.</param>
        /// <param name="courseId">Initial value of the courseId property.</param>
        /// <param name="statusId">Initial value of the statusId property.</param>
        public static ScheduledClass CreateScheduledClass(global::System.Int32 scheduledClassId, global::System.Int32 courseId, global::System.Int32 statusId)
        {
            ScheduledClass scheduledClass = new ScheduledClass();
            scheduledClass.scheduledClassId = scheduledClassId;
            scheduledClass.courseId = courseId;
            scheduledClass.statusId = statusId;
            return scheduledClass;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 scheduledClassId
        {
            get
            {
                return _scheduledClassId;
            }
            set
            {
                if (_scheduledClassId != value)
                {
                    OnscheduledClassIdChanging(value);
                    ReportPropertyChanging("scheduledClassId");
                    _scheduledClassId = StructuralObject.SetValidValue(value, "scheduledClassId");
                    ReportPropertyChanged("scheduledClassId");
                    OnscheduledClassIdChanged();
                }
            }
        }
        private global::System.Int32 _scheduledClassId;
        partial void OnscheduledClassIdChanging(global::System.Int32 value);
        partial void OnscheduledClassIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 courseId
        {
            get
            {
                return _courseId;
            }
            set
            {
                OncourseIdChanging(value);
                ReportPropertyChanging("courseId");
                _courseId = StructuralObject.SetValidValue(value, "courseId");
                ReportPropertyChanged("courseId");
                OncourseIdChanged();
            }
        }
        private global::System.Int32 _courseId;
        partial void OncourseIdChanging(global::System.Int32 value);
        partial void OncourseIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> startDate
        {
            get
            {
                return _startDate;
            }
            set
            {
                OnstartDateChanging(value);
                ReportPropertyChanging("startDate");
                _startDate = StructuralObject.SetValidValue(value, "startDate");
                ReportPropertyChanged("startDate");
                OnstartDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _startDate;
        partial void OnstartDateChanging(Nullable<global::System.DateTime> value);
        partial void OnstartDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> endDate
        {
            get
            {
                return _endDate;
            }
            set
            {
                OnendDateChanging(value);
                ReportPropertyChanging("endDate");
                _endDate = StructuralObject.SetValidValue(value, "endDate");
                ReportPropertyChanged("endDate");
                OnendDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _endDate;
        partial void OnendDateChanging(Nullable<global::System.DateTime> value);
        partial void OnendDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> creditHours
        {
            get
            {
                return _creditHours;
            }
            set
            {
                OncreditHoursChanging(value);
                ReportPropertyChanging("creditHours");
                _creditHours = StructuralObject.SetValidValue(value, "creditHours");
                ReportPropertyChanged("creditHours");
                OncreditHoursChanged();
            }
        }
        private Nullable<global::System.Double> _creditHours;
        partial void OncreditHoursChanging(Nullable<global::System.Double> value);
        partial void OncreditHoursChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String instructorName
        {
            get
            {
                return _instructorName;
            }
            set
            {
                OninstructorNameChanging(value);
                ReportPropertyChanging("instructorName");
                _instructorName = StructuralObject.SetValidValue(value, true, "instructorName");
                ReportPropertyChanged("instructorName");
                OninstructorNameChanged();
            }
        }
        private global::System.String _instructorName;
        partial void OninstructorNameChanging(global::System.String value);
        partial void OninstructorNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String location
        {
            get
            {
                return _location;
            }
            set
            {
                OnlocationChanging(value);
                ReportPropertyChanging("location");
                _location = StructuralObject.SetValidValue(value, true, "location");
                ReportPropertyChanged("location");
                OnlocationChanged();
            }
        }
        private global::System.String _location;
        partial void OnlocationChanging(global::System.String value);
        partial void OnlocationChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 statusId
        {
            get
            {
                return _statusId;
            }
            set
            {
                OnstatusIdChanging(value);
                ReportPropertyChanging("statusId");
                _statusId = StructuralObject.SetValidValue(value, "statusId");
                ReportPropertyChanged("statusId");
                OnstatusIdChanged();
            }
        }
        private global::System.Int32 _statusId;
        partial void OnstatusIdChanging(global::System.Int32 value);
        partial void OnstatusIdChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SATModel", "FK_ScheduledClasses_Courses", "Courses")]
        public Cours Cours
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Cours>("SATModel.FK_ScheduledClasses_Courses", "Courses").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Cours>("SATModel.FK_ScheduledClasses_Courses", "Courses").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Cours> CoursReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Cours>("SATModel.FK_ScheduledClasses_Courses", "Courses");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Cours>("SATModel.FK_ScheduledClasses_Courses", "Courses", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SATModel", "FK_Enrollments_ScheduledClasses", "Enrollments")]
        public EntityCollection<Enrollment> Enrollments
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Enrollment>("SATModel.FK_Enrollments_ScheduledClasses", "Enrollments");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Enrollment>("SATModel.FK_Enrollments_ScheduledClasses", "Enrollments", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SATModel", "FK_ScheduledClasses_ScheduledClassStatus1", "ScheduledClassStatus")]
        public ScheduledClassStatu ScheduledClassStatu
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ScheduledClassStatu>("SATModel.FK_ScheduledClasses_ScheduledClassStatus1", "ScheduledClassStatus").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ScheduledClassStatu>("SATModel.FK_ScheduledClasses_ScheduledClassStatus1", "ScheduledClassStatus").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<ScheduledClassStatu> ScheduledClassStatuReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ScheduledClassStatu>("SATModel.FK_ScheduledClasses_ScheduledClassStatus1", "ScheduledClassStatus");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<ScheduledClassStatu>("SATModel.FK_ScheduledClasses_ScheduledClassStatus1", "ScheduledClassStatus", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SATModel", Name="ScheduledClassStatu")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ScheduledClassStatu : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ScheduledClassStatu object.
        /// </summary>
        /// <param name="sCSID">Initial value of the SCSID property.</param>
        /// <param name="sCSName">Initial value of the SCSName property.</param>
        public static ScheduledClassStatu CreateScheduledClassStatu(global::System.Int32 sCSID, global::System.String sCSName)
        {
            ScheduledClassStatu scheduledClassStatu = new ScheduledClassStatu();
            scheduledClassStatu.SCSID = sCSID;
            scheduledClassStatu.SCSName = sCSName;
            return scheduledClassStatu;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 SCSID
        {
            get
            {
                return _SCSID;
            }
            set
            {
                if (_SCSID != value)
                {
                    OnSCSIDChanging(value);
                    ReportPropertyChanging("SCSID");
                    _SCSID = StructuralObject.SetValidValue(value, "SCSID");
                    ReportPropertyChanged("SCSID");
                    OnSCSIDChanged();
                }
            }
        }
        private global::System.Int32 _SCSID;
        partial void OnSCSIDChanging(global::System.Int32 value);
        partial void OnSCSIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String SCSName
        {
            get
            {
                return _SCSName;
            }
            set
            {
                OnSCSNameChanging(value);
                ReportPropertyChanging("SCSName");
                _SCSName = StructuralObject.SetValidValue(value, false, "SCSName");
                ReportPropertyChanged("SCSName");
                OnSCSNameChanged();
            }
        }
        private global::System.String _SCSName;
        partial void OnSCSNameChanging(global::System.String value);
        partial void OnSCSNameChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SATModel", "FK_ScheduledClasses_ScheduledClassStatus1", "ScheduledClasses")]
        public EntityCollection<ScheduledClass> ScheduledClasses
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<ScheduledClass>("SATModel.FK_ScheduledClasses_ScheduledClassStatus1", "ScheduledClasses");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<ScheduledClass>("SATModel.FK_ScheduledClasses_ScheduledClassStatus1", "ScheduledClasses", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SATModel", Name="Student")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Student : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Student object.
        /// </summary>
        /// <param name="studentId">Initial value of the studentId property.</param>
        /// <param name="firstName">Initial value of the firstName property.</param>
        /// <param name="lastName">Initial value of the lastName property.</param>
        /// <param name="statusId">Initial value of the statusId property.</param>
        public static Student CreateStudent(global::System.Int32 studentId, global::System.String firstName, global::System.String lastName, global::System.Int32 statusId)
        {
            Student student = new Student();
            student.studentId = studentId;
            student.firstName = firstName;
            student.lastName = lastName;
            student.statusId = statusId;
            return student;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 studentId
        {
            get
            {
                return _studentId;
            }
            set
            {
                if (_studentId != value)
                {
                    OnstudentIdChanging(value);
                    ReportPropertyChanging("studentId");
                    _studentId = StructuralObject.SetValidValue(value, "studentId");
                    ReportPropertyChanged("studentId");
                    OnstudentIdChanged();
                }
            }
        }
        private global::System.Int32 _studentId;
        partial void OnstudentIdChanging(global::System.Int32 value);
        partial void OnstudentIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String firstName
        {
            get
            {
                return _firstName;
            }
            set
            {
                OnfirstNameChanging(value);
                ReportPropertyChanging("firstName");
                _firstName = StructuralObject.SetValidValue(value, false, "firstName");
                ReportPropertyChanged("firstName");
                OnfirstNameChanged();
            }
        }
        private global::System.String _firstName;
        partial void OnfirstNameChanging(global::System.String value);
        partial void OnfirstNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String lastName
        {
            get
            {
                return _lastName;
            }
            set
            {
                OnlastNameChanging(value);
                ReportPropertyChanging("lastName");
                _lastName = StructuralObject.SetValidValue(value, false, "lastName");
                ReportPropertyChanged("lastName");
                OnlastNameChanged();
            }
        }
        private global::System.String _lastName;
        partial void OnlastNameChanging(global::System.String value);
        partial void OnlastNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String major
        {
            get
            {
                return _major;
            }
            set
            {
                OnmajorChanging(value);
                ReportPropertyChanging("major");
                _major = StructuralObject.SetValidValue(value, true, "major");
                ReportPropertyChanged("major");
                OnmajorChanged();
            }
        }
        private global::System.String _major;
        partial void OnmajorChanging(global::System.String value);
        partial void OnmajorChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String classification
        {
            get
            {
                return _classification;
            }
            set
            {
                OnclassificationChanging(value);
                ReportPropertyChanging("classification");
                _classification = StructuralObject.SetValidValue(value, true, "classification");
                ReportPropertyChanged("classification");
                OnclassificationChanged();
            }
        }
        private global::System.String _classification;
        partial void OnclassificationChanging(global::System.String value);
        partial void OnclassificationChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String address
        {
            get
            {
                return _address;
            }
            set
            {
                OnaddressChanging(value);
                ReportPropertyChanging("address");
                _address = StructuralObject.SetValidValue(value, true, "address");
                ReportPropertyChanged("address");
                OnaddressChanged();
            }
        }
        private global::System.String _address;
        partial void OnaddressChanging(global::System.String value);
        partial void OnaddressChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String city
        {
            get
            {
                return _city;
            }
            set
            {
                OncityChanging(value);
                ReportPropertyChanging("city");
                _city = StructuralObject.SetValidValue(value, true, "city");
                ReportPropertyChanged("city");
                OncityChanged();
            }
        }
        private global::System.String _city;
        partial void OncityChanging(global::System.String value);
        partial void OncityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String state
        {
            get
            {
                return _state;
            }
            set
            {
                OnstateChanging(value);
                ReportPropertyChanging("state");
                _state = StructuralObject.SetValidValue(value, true, "state");
                ReportPropertyChanged("state");
                OnstateChanged();
            }
        }
        private global::System.String _state;
        partial void OnstateChanging(global::System.String value);
        partial void OnstateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String zip
        {
            get
            {
                return _zip;
            }
            set
            {
                OnzipChanging(value);
                ReportPropertyChanging("zip");
                _zip = StructuralObject.SetValidValue(value, true, "zip");
                ReportPropertyChanged("zip");
                OnzipChanged();
            }
        }
        private global::System.String _zip;
        partial void OnzipChanging(global::System.String value);
        partial void OnzipChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String phone
        {
            get
            {
                return _phone;
            }
            set
            {
                OnphoneChanging(value);
                ReportPropertyChanging("phone");
                _phone = StructuralObject.SetValidValue(value, true, "phone");
                ReportPropertyChanged("phone");
                OnphoneChanged();
            }
        }
        private global::System.String _phone;
        partial void OnphoneChanging(global::System.String value);
        partial void OnphoneChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String email
        {
            get
            {
                return _email;
            }
            set
            {
                OnemailChanging(value);
                ReportPropertyChanging("email");
                _email = StructuralObject.SetValidValue(value, true, "email");
                ReportPropertyChanged("email");
                OnemailChanged();
            }
        }
        private global::System.String _email;
        partial void OnemailChanging(global::System.String value);
        partial void OnemailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 statusId
        {
            get
            {
                return _statusId;
            }
            set
            {
                OnstatusIdChanging(value);
                ReportPropertyChanging("statusId");
                _statusId = StructuralObject.SetValidValue(value, "statusId");
                ReportPropertyChanged("statusId");
                OnstatusIdChanged();
            }
        }
        private global::System.Int32 _statusId;
        partial void OnstatusIdChanging(global::System.Int32 value);
        partial void OnstatusIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String pictureUrl
        {
            get
            {
                return _pictureUrl;
            }
            set
            {
                OnpictureUrlChanging(value);
                ReportPropertyChanging("pictureUrl");
                _pictureUrl = StructuralObject.SetValidValue(value, true, "pictureUrl");
                ReportPropertyChanged("pictureUrl");
                OnpictureUrlChanged();
            }
        }
        private global::System.String _pictureUrl;
        partial void OnpictureUrlChanging(global::System.String value);
        partial void OnpictureUrlChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SATModel", "FK_Enrollments_Students", "Enrollments")]
        public EntityCollection<Enrollment> Enrollments
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Enrollment>("SATModel.FK_Enrollments_Students", "Enrollments");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Enrollment>("SATModel.FK_Enrollments_Students", "Enrollments", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SATModel", "FK_Students_StudentStatus", "StudentStatus")]
        public StudentStatu StudentStatu
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<StudentStatu>("SATModel.FK_Students_StudentStatus", "StudentStatus").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<StudentStatu>("SATModel.FK_Students_StudentStatus", "StudentStatus").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<StudentStatu> StudentStatuReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<StudentStatu>("SATModel.FK_Students_StudentStatus", "StudentStatus");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<StudentStatu>("SATModel.FK_Students_StudentStatus", "StudentStatus", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SATModel", Name="StudentStatu")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class StudentStatu : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new StudentStatu object.
        /// </summary>
        /// <param name="sSID">Initial value of the SSID property.</param>
        /// <param name="sSName">Initial value of the SSName property.</param>
        public static StudentStatu CreateStudentStatu(global::System.Int32 sSID, global::System.String sSName)
        {
            StudentStatu studentStatu = new StudentStatu();
            studentStatu.SSID = sSID;
            studentStatu.SSName = sSName;
            return studentStatu;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 SSID
        {
            get
            {
                return _SSID;
            }
            set
            {
                if (_SSID != value)
                {
                    OnSSIDChanging(value);
                    ReportPropertyChanging("SSID");
                    _SSID = StructuralObject.SetValidValue(value, "SSID");
                    ReportPropertyChanged("SSID");
                    OnSSIDChanged();
                }
            }
        }
        private global::System.Int32 _SSID;
        partial void OnSSIDChanging(global::System.Int32 value);
        partial void OnSSIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String SSName
        {
            get
            {
                return _SSName;
            }
            set
            {
                OnSSNameChanging(value);
                ReportPropertyChanging("SSName");
                _SSName = StructuralObject.SetValidValue(value, false, "SSName");
                ReportPropertyChanged("SSName");
                OnSSNameChanged();
            }
        }
        private global::System.String _SSName;
        partial void OnSSNameChanging(global::System.String value);
        partial void OnSSNameChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SATModel", "FK_Students_StudentStatus", "Students")]
        public EntityCollection<Student> Students
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Student>("SATModel.FK_Students_StudentStatus", "Students");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Student>("SATModel.FK_Students_StudentStatus", "Students", value);
                }
            }
        }

        #endregion

    }

    #endregion

}
